# Generated by Django 5.1.4 on 2025-01-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('user', '0002_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reposted_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='reposted_by', to='post.post'),
        ),
    ]
