# Generated by Django 5.1.4 on 2025-01-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('user', '0003_alter_profile_reposted_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reposted_posts',
            field=models.ManyToManyField(blank=True, related_name='reposted_by', to='post.post'),
        ),
    ]
